#!/usr/bin/python

import sys
import os
import getopt
import mnemosyne

if __name__ == '__main__':
    shortopts = 'f'
    longopts = ['force']

    try:
        opts, args = getopt.getopt(sys.argv[1:], shortopts, longopts)
    except getopt.GetoptError, e:
        print >>sys.stderr, 'error: %s' % e
        sys.exit(1)

    force=False
    for opt, arg in opts:
        if opt in ('--force', '-f'):
            force = True

    try:
        config = args[0]
    except IndexError:
        config = os.path.join(os.environ['HOME'], 'Mnemosyne', 'config.py')

    muse = mnemosyne.Muse(config, force)
    muse.sing()
